version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"   # RabbitMQ Management UI
      - "5672:5672"     # RabbitMQ Broker port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Safaa@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  ingestion-service:
    build:
      context: ./IngestionService
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5001:80"

  preprocessing-service:
    build:
      context: ./PreprocessingService
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5002:80"

  aggregation-service:
    build:
      context: ./AggregationService
    depends_on:
      - rabbitmq
      - sqlserver
    ports:
      - "5003:80"
